# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20181230_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
