# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0005_auto_20190221_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
