# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UserImage',
        ),
    ]
