# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-12 15:42
from __future__ import unicode_literals

import catalog.file.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_auto_20190409_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=catalog.file.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=catalog.file.models.get_file_path),
        ),
    ]
