# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20190412_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
