# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 10:06
from __future__ import unicode_literals

import catalog.file.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_auto_20191013_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=catalog.file.models.get_file_path)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
