# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_urlimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlimage',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
