from django.conf.urls import url
from catalog.post import views

urlpatterns = [
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailsView.as_view()),
    url(r'^get-post-by-slug/(?P<subject>.+)/(?P<sslug>.+)/(?P<slug>.+)/$', views.PostBySlugView.as_view()),
    url(r'^delete-post/(?P<pk>[0-9]+)/$', views.DeletePostView.as_view()),
    url(r'^create-post/', views.CreatePostView.as_view()),
    url(r'^users-posts-by-page/(?P<page>[0-9]+)/$', views.UsersPostsByPageView.as_view()),
    url(r'^posts-for-user-by-page/(?P<page>[0-9]+)/$', views.PostsForUserByPageView.as_view()),
    url(r'^get-filtered-posts-by-page/(?P<page>[0-9]+)/$', views.FilteredPostsByPageView.as_view()),
    url(r'^user-feed/(?P<page>[0-9]+)/$', views.UserFeedView.as_view()),
    url(r'^get_url_preview/', views.UrlPreviewView.as_view()),
    url(r'^get-post-categories/(?P<post>.+)/$', views.PostCategoriesView.as_view()),
    url(r'^post-types/', views.PostTypesListView.as_view()),
    url(r'^create-post-comment/', views.CreatePostCommentView.as_view()),
    url(r'^delete-post-comment/(?P<pk>[0-9]+)/$', views.DeletePostCommentView.as_view()),
    url(r'^update-post-comment/(?P<pk>[0-9]+)/$', views.UpdatePostCommentView.as_view()),
    url(r'^post-comments-by-page/(?P<post>[0-9]+)/(?P<parent>[0-9]+)/(?P<page>[0-9]+)/$',
        views.PostCommentsByPageView.as_view()),
    url(r'^create-post-like/', views.CreatePostLikeView.as_view()),
    url(r'^delete-post-like/(?P<post>.+)/$', views.DeletePostLikeView.as_view()),
    url(r'^post-likes-by-page/(?P<page>[0-9]+)/$',
        views.PostLikesByPageView.as_view()),
    url(r'^create-post-comment-like/', views.CreatePostCommentLikeView.as_view()),
    url(r'^delete-post-comment-like/(?P<comment>.+)/$', views.DeletePostCommentLikeView.as_view()),
    url(r'^post-comment-likes-by-page/(?P<page>[0-9]+)/$',
        views.PostCommentLikesByPageView.as_view()),
    url(r'^likes-count/', views.LikesCountView.as_view()),
    url(r'^change-post-status/(?P<post>[0-9]+)/(?P<published>.+)/$',
        views.ChangePostStatusView.as_view()),
    url(r'^get-post/(?P<pk>[0-9]+)/$', views.PostView.as_view()),
    url(r'^applicant-statuses/', views.ApplicantStatusListView.as_view()),
    url(r'^create-application/', views.CreateApplicationView.as_view()),
    url(r'^post-applicants/(?P<post>[0-9]+)/(?P<page>[0-9]+)/(?P<order>.+)/$', views.PostApplicantsView.as_view()),
    url(r'^user-applicants/(?P<user_type>.+)/(?P<page>[0-9]+)/(?P<order>.+)/$', views.UserApplicantsView.as_view()),
    url(r'^company-applicants/(?P<company>[0-9]+)/(?P<page>[0-9]+)/(?P<order>.+)/$',
        views.CompanyApplicantsView.as_view()),
    url(r'^set-applicant-rating/(?P<applicant>[0-9]+)/$', views.SetApplicantRatingView.as_view()),
    url(r'^update-applicant-comment/(?P<applicant>[0-9]+)/$', views.UpdateApplicantCommentView.as_view()),
    url(r'^update-applicant-status/(?P<applicant>[0-9]+)/$', views.UpdateApplicantStatusView.as_view()),

    url(r'^post-respond-statuses/', views.PostRespondStatusListView.as_view()),
    url(r'^create-post-respond/', views.CreatePostRespondView.as_view()),
    url(r'^post-responds/(?P<post>[0-9]+)/(?P<page>[0-9]+)/(?P<order>.+)/$', views.PostRespondsView.as_view()),
    url(r'^user-responds/(?P<type>.+)/(?P<user_type>.+)/(?P<page>[0-9]+)/(?P<order>.+)/$',
        views.UserRespondsView.as_view()),
    url(r'^company-responds/(?P<company>[0-9]+)/(?P<type>.+)/(?P<user_type>.+)/(?P<page>[0-9]+)/(?P<order>.+)/$',
        views.CompanyRespondsView.as_view()),
    url(r'^set-post-respond-rating/(?P<respond>[0-9]+)/$', views.SetPostRespondRatingView.as_view()),
    url(r'^update-post-respond-comment/(?P<respond>[0-9]+)/$', views.UpdatePostRespondCommentView.as_view()),
    url(r'^update-post-respond-status/(?P<respond>[0-9]+)/$', views.UpdatePostRespondStatusView.as_view()),
    url(r'^create-favorite-post/', views.CreateFavoritePostView.as_view()),
    url(r'^delete-favorite-post/(?P<post>[0-9]+)/$', views.DeleteFavoritePostView.as_view()),
    url(r'^favorite-posts-by-page/(?P<page>[0-9]+)/$', views.FavoritePostsByPageView.as_view()),
    url(r'^vote/', views.CreatePostOptionVoteView.as_view()),
    url(r'^delete-vote/(?P<post>.+)/(?P<option>[0-9]+)/$', views.DeletePostOptionVoteView.as_view()),
    url(r'^post-option-votes/(?P<page>[0-9]+)/$',
        views.PostOptionVotesByPageView.as_view()),
    url(r'^get-universal-filter/(?P<query>.+)/(?P<language>.+)/$', views.FormUniversalFilterView.as_view()),
    url(r'^get-feed-filter/(?P<query>.+)/$', views.FeedFilterView.as_view()),
    url(r'^create-article/', views.CreateArticleView.as_view()),
    url(r'^update-article-in-language/(?P<post>[0-9]+)/(?P<language>.+)/$', views.UpdateArticleView.as_view()),
    url(r'^delete-article-language/(?P<pk>[0-9]+)/(?P<language>.+)/$',
        views.DeleteArticleLanguageView.as_view()),
    url(r'^publish-article/', views.PublishArticleView.as_view()),
    url(r'^get-article-by-slug/(?P<subject>.+)/(?P<sslug>.+)/(?P<slug>.+)/$', views.ArticleBySlugView.as_view()),
    url(r'^follow-filter/', views.FollowFilterView.as_view()),
    url(r'^unfollow-filter/(?P<filter>[0-9]+)/$', views.DeleteFollowFilterView.as_view()),
    url(r'^create-post-impression/', views.CreatePostImpressionView.as_view()),
    url(r'^create-post-engagement/', views.CreatePostEngagementView.as_view()),

]
