from django.conf.urls import url
from catalog.community import views

urlpatterns = [

    url(r'^get-community-categories/(?P<community>.+)/(?P<parent>.+)/$', views.CommunityParentCategoriesView.as_view()),
    url(r'^get-community-categories-view/(?P<community>.+)/$', views.CommunityCategoriesView.as_view()),
    url(r'^create-community-category/', views.CreateCommunityCategoryView.as_view()),
    url(r'^delete-community-category/(?P<community>[0-9]+)/(?P<category>.+)/$',
        views.DeleteCommunityCategoryView.as_view()),
    url(r'^leave-community/(?P<community>[0-9]+)/$', views.LeaveCommunityView.as_view()),
    url(r'^leave-company-community/(?P<pk>[0-9]+)/$', views.LeaveCompanyCommunityView.as_view()),
    url(r'^get-community-details/(?P<pk>[0-9]+)/$', views.CommunityDetailsView.as_view()),
    url(r'^get-community-details-in-language/(?P<pk>[0-9]+)/(?P<language>.+)/$',
        views.CommunityDetailsInLanguageView.as_view()),
    url(r'^update-community-details/(?P<pk>[0-9]+)/(?P<language>.+)/$', views.UpdateCommunityDetailsView.as_view()),
    url(r'^delete-community/(?P<pk>[0-9]+)/$', views.DeleteCommunityView.as_view()),
    url(r'^create-community/', views.CreateCommunityView.as_view()),
    url(r'^communities-by-page/(?P<page>[0-9]+)/$', views.CommunitiesByPageView.as_view()),
    url(r'^communities-count/', views.CommunitiesCountView.as_view()),
    url(r'^check-delete-community-admin-status/', views.CheckDeleteCommunityAdminStatusView.as_view()),
    url(r'^get-communities-by-name/(?P<name>.+)/(?P<language>.+)/$', views.CommunitiesByNameView.as_view()),
    url(r'^get-community-members/(?P<community>.+)/(?P<page>[0-9]+)/$', views.CommunityMembersView.as_view()),
    url(r'^get-community-members-count/(?P<community>.+)/$', views.CommunityMembersCountView.as_view()),
    url(r'^get-community-companies-count/(?P<community>.+)/$', views.CommunityCompaniesCountView.as_view()),
    url(r'^get-community-member-permisions/(?P<user>.+)/(?P<community>.+)/$', views.MemberPermisionsView.as_view()),
    url(r'^delete-community-member/(?P<user>.+)/(?P<community>.+)/$', views.DeleteCommunityMemberView.as_view()),
    url(r'^delete-community-company/(?P<company>.+)/(?P<community>.+)/$', views.DeleteCommunityCompanyView.as_view()),
    url(r'^create-community-member/', views.CreateCommunityMemberView.as_view()),
    # url(r'^update-community-member/(?P<pk>[0-9]+)/$', views.CommunityMemberUpdateView.as_view()),
    url(r'^get-community-companies/(?P<community>.+)/(?P<page>[0-9]+)/$', views.CommunityCompaniesView.as_view()),
    url(r'^create-community-company/', views.CreateCommunityCompanyView.as_view()),
    url(r'^update-community-company/(?P<pk>[0-9]+)/$', views.CommunityCompanyUpdateView.as_view()),
    url(r'^get-community-invitations/(?P<community>.+)/$', views.CommunityInvitationsView.as_view()),
    url(r'^admin-create-community-invitation/', views.AdminCreateCommunityInvitationView.as_view()),
    url(r'^user-create-community-invitation/', views.UserCreateCommunityInvitationView.as_view()),
    url(r'^user-accept-community-invitation/', views.UserAcceptCommunityInvitationView.as_view()),
    url(r'^update-community-invitation/(?P<pk>[0-9]+)/$', views.CommunityInvitationUpdateView.as_view()),
    url(r'^delete-community-invitation/(?P<pk>[0-9]+)/$', views.DeleteCommunityInvitationView.as_view()),
    url(r'^delete-community-invitation-by-user/(?P<user>.+)/(?P<community>.+)/$',
        views.DeleteCommunityInvitationByUserView.as_view()),
    url(r'^get-community-invitation-for-member/(?P<community>.+)/(?P<user>.+)/$',
        views.GetInvitationForMemberView.as_view()),
    url(r'^get-community-invitation-for-company/(?P<community>.+)/(?P<company>.+)/$',
        views.GetInvitationForCompanyView.as_view()),
    url(r'^get-community-company/(?P<community>.+)/(?P<company>.+)/$',
        views.GetCommunityCompanyView.as_view()),
    url(r'^get-adminuser-companies-in-community-invitations/(?P<user>.+)/(?P<community>.+)/$',
        views.UserCompaniesInCommunityInvitationsView.as_view()),
    url(r'^set-community-member-admin-status/(?P<community>.+)/(?P<user>.+)/$',
        views.SetCommunityAdminStatusView.as_view()),

]
