# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.IntegerField(choices=[(1, '1. answer'), (2, '2. page'), (3, '3. mockup'), (4, '4. user')])),
                ('object_id', models.IntegerField()),
                ('url', models.URLField()),
                ('image_url', models.CharField(blank=True, max_length=350, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, max_length=2500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
