# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180928_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.PostType'),
        ),
    ]
