# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttype',
            name='color',
        ),
    ]
