# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20181001_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
