# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20181006_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='object_type',
            field=models.IntegerField(blank=True, choices=[(1, '1. answer'), (2, '2. page'), (3, '3. mockup'), (4, '4. user')], null=True),
        ),
    ]
