# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20181025_0956'),
        ('product', '0011_product_company'),
        ('post', '0012_auto_20181010_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='object_type',
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
