# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20181117_0841'),
        ('post', '0015_auto_20181101_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
