# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20180925_0944'),
        ('post', '0016_post_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='post_category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category'),
        ),
    ]
