# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_auto_20181226_1321'),
        ('file', '0004_auto_20181230_1059'),
        ('post', '0017_auto_20190119_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Country')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_request', to='post.Post')),
                ('price_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='PostRequestPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_request_positions', to='post.Post')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.UnitType')),
            ],
        ),
    ]
