# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_postdocument_postrequest_postrequestposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
