# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20190120_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrequestposition',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_request_positions', to='post.Post'),
        ),
    ]
