# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20181230_1059'),
        ('post', '0022_auto_20190120_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Post')),
            ],
        ),
    ]
