# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='post',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='postimage',
            order_with_respect_to='post',
        ),
    ]
