# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_auto_20190206_1509'),
        ('post', '0025_post_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('user_attribute', models.BooleanField(default=True)),
                ('multiple', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.Attribute')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_attributes', to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(max_length=150)),
                ('value_number', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('post_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='post.PostAttribute')),
                ('value_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.AttributeValue')),
            ],
        ),
    ]
