# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0026_postattribute_postattributevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattribute',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='post.Post'),
        ),
    ]
