# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_auto_20190207_1100'),
        ('post', '0028_remove_postattributevalue_value_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattributevalue',
            name='value_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.AttributeValue'),
        ),
    ]
