# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_postattributevalue_value_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattributevalue',
            name='value_string',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
