# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_auto_20190208_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattributevalue',
            name='value_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postattributevalue',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
