# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0035_auto_20190210_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffering',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
