# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0024_auto_20181226_1321'),
        ('category', '0013_auto_20190206_1337'),
        ('post', '0036_postoffering_price_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPostFilterValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_post_values', to='category.Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_post_values', to='general.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_post_values', to='general.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='postoffering',
            name='city',
        ),
        migrations.RemoveField(
            model_name='postoffering',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='postoffering',
            name='country',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.City'),
        ),
        migrations.AddField(
            model_name='post',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Country'),
        ),
    ]
