# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_auto_20190213_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoffering',
            name='id',
        ),
        migrations.RemoveField(
            model_name='postrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postattribute',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postattributevalue',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postdocument',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postoffering',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post_offering', serialize=False, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='postrequest',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post_request', serialize=False, to='post.Post'),
        ),
        migrations.AlterField(
            model_name='postrequestposition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
