# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-24 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_auto_20190221_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
