# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0045_posteventsqty_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='file',
        ),
    ]
