# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0049_auto_20190523_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
