# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-14 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0050_auto_20190714_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
