# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_auto_20190717_1251'),
        ('post', '0052_auto_20190714_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='post_job', serialize=False, to='post.Post')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.JobFunction')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.JobType')),
                ('salary_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Currency')),
                ('seniority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.SeniorityLabel')),
            ],
        ),
    ]
