# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0053_postjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='feed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
