# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 12:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0008_auto_20190412_1542'),
        ('messaging', '0009_auto_20190724_1714'),
        ('post', '0054_posttype_feed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('salary_exp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reviewed', models.BooleanField(default=False, null=None)),
                ('interview', models.BooleanField(default=False, null=None)),
                ('rejected', models.BooleanField(default=False, null=None)),
                ('approved', models.BooleanField(default=False, null=None)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.Chat')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='post.Post')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set([('post', 'user')]),
        ),
    ]
