# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-30 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0056_postjob_resume_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
