# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0057_auto_20190730_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteventsqty',
            name='applicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posteventsqty',
            name='new_applicants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
