# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20190724_1714'),
        ('post', '0058_auto_20190801_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantChat',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat', serialize=False, to='post.Applicant')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='messaging.Chat')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='chat',
        ),
        migrations.AlterUniqueTogether(
            name='applicantchat',
            unique_together=set([('applicant', 'chat')]),
        ),
    ]
