# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0060_auto_20190808_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.ApplicantStatus'),
        ),
    ]
