# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0061_auto_20190808_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantstatus',
            name='icon',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
