# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0062_applicantstatus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantstatus',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
