# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0063_applicantstatus_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantstatus',
            old_name='color',
            new_name='color_class',
        ),
    ]
