# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0065_auto_20190814_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteventsqty',
            name='new_responds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posteventsqty',
            name='responds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
