# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0067_auto_20190814_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrespond',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_responds', to='company.Company'),
        ),
    ]
