# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0069_auto_20190909_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttypetranslation',
            name='name_plural',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
