# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0073_auto_20190930_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='object_related',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
