# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0075_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoption',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
