# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20191003_0728'),
        ('company', '0025_auto_20191001_1444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0078_auto_20191005_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='postreview',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='related_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_reviews', to='company.Company'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='product.Product'),
        ),
        migrations.AddField(
            model_name='post',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
