# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0080_post_multi_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffering',
            name='type',
            field=models.IntegerField(choices=[(1, '1. sales'), (2, '2. rent'), (3, '2. promotion')], default=1),
        ),
    ]
