# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0081_auto_20191007_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffering',
            name='discount',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='discount_price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='discount_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='discount_price_usd_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='one_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='postoffering',
            name='price_usd_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
