# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0082_auto_20191008_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoffering',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
