# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0032_auto_20190719_1019'),
        ('post', '0083_auto_20191008_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoffering',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.UnitType'),
        ),
    ]
