# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0086_auto_20191012_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
