# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0090_auto_20191024_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
