# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0092_auto_20191024_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='create_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
