# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0093_auto_20191024_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
