# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0095_auto_20191027_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video_url',
            field=models.BooleanField(default=False),
        ),
    ]
