# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0097_auto_20200216_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.UserImage'),
        ),
    ]
