# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0098_auto_20200304_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
