# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-17 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0099_auto_20200304_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
