# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-17 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0100_post_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommenturlpreview',
            name='site_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
