# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0101_postcommenturlpreview_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postseodata',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
