# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0103_postcomment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
