# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-27 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0037_auto_20200426_1414'),
        ('post', '0105_auto_20200415_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='suggested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.SuggestedCategory'),
        ),
    ]
