# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0106_post_suggested_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.File'),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='salary_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Currency'),
        ),
        migrations.AlterField(
            model_name='postrequestposition',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.UnitType'),
        ),
    ]
