# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0110_auto_20200807_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='default_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
