# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-07 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0111_auto_20200807_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='default_title',
        ),
    ]
