# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-02 08:44
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('post', '0116_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
