# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0118_auto_20200902_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='seo_title_draft',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
