# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0120_article_allow_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='allow_index',
            field=models.BooleanField(default=False),
        ),
    ]
