# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0121_auto_20200906_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_index',
            field=models.BooleanField(default=False),
        ),
    ]
