# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0122_post_allow_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
