# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0124_auto_20200907_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
