# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0126_auto_20200922_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postseodatafollower',
            old_name='data',
            new_name='filter',
        ),
        migrations.AlterUniqueTogether(
            name='postseodatafollower',
            unique_together=set([('filter', 'user')]),
        ),
    ]
