# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0127_auto_20200924_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFilterFeed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostSEOData')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='post.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='postseodatafollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postfilterfeed',
            unique_together=set([('filter', 'post')]),
        ),
    ]
