# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-01 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0130_auto_20201001_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserViews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('impression', models.BooleanField(default=True)),
                ('view', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
