# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-01 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0131_postuserviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuserviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
