# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-01 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0132_auto_20201001_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteventsqty',
            name='user_impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posteventsqty',
            name='user_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='postuserviews',
            unique_together=set([('post', 'user', 'view', 'create_date')]),
        ),
    ]
