# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-02 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0133_auto_20201001_1326'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postuserviews',
            unique_together=set([('post', 'user', 'view', 'impression', 'create_date')]),
        ),
    ]
