# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-03 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0136_auto_20201003_1055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUserEngagements',
            new_name='PostUserEngagement',
        ),
    ]
