# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-03 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0137_auto_20201003_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUserViews',
            new_name='PostUserImpression',
        ),
    ]
