# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-05 09:28
from __future__ import unicode_literals

import catalog.post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0143_auto_20201003_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuserengagement',
            name='timestamp',
            field=models.CharField(default=catalog.post.models.get_date, max_length=25),
        ),
        migrations.AddField(
            model_name='postuserimpression',
            name='timestamp',
            field=models.CharField(default=catalog.post.models.get_date, max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='postuserengagement',
            unique_together=set([('post', 'user', 'timestamp', 'type')]),
        ),
    ]
