# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-05 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0145_auto_20201005_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuserengagement',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postuserimpression',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postuserengagement',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='postuserengagement',
            unique_together=set([('post', 'user', 'timestamp', 'create_date', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='postuserimpression',
            unique_together=set([('post', 'user', 'view', 'impression', 'timestamp', 'create_date')]),
        ),
    ]
