# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-05 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0146_auto_20201005_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postuserimpression',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
