# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0147_auto_20201005_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPosts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_posts', to='post.Post')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_posts', to='post.Post')),
            ],
        ),
    ]
