# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0148_relatedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedposts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
