# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-11 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0149_auto_20201010_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedposts',
            options={'ordering': ('-id',)},
        ),
    ]
