# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-11 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0150_auto_20201011_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedposts',
            options={'ordering': ('id',)},
        ),
    ]
