# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0151_auto_20201011_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedPosts',
            new_name='RelatedPost',
        ),
    ]
