# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0153_auto_20201011_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='manual_related_posts',
            field=models.BooleanField(default=False),
        ),
    ]
