# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-12 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0154_post_manual_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpost',
            name='comment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
