# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0155_relatedpost_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='promotion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='promotion_grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
