# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-14 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0156_auto_20201214_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='promotion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='promotion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='promotion_grade',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='postoffering',
            name='price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Currency'),
        ),
        migrations.AlterField(
            model_name='postoffering',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.UnitType'),
        ),
    ]
