# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0157_auto_20201214_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prohibited',
            field=models.BooleanField(default=False),
        ),
    ]
