# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-26 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0158_post_prohibited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='promotion_grade',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
