# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile_Categories',
            new_name='UserProfileCategories',
        ),
    ]
