# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20180925_0944'),
        ('user_profile', '0005_auto_20180926_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofilecategories',
            unique_together=set([('profile', 'category', 'interest')]),
        ),
    ]
