# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20180926_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileCategories',
            new_name='UserProfileCategory',
        ),
    ]
