# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 08:23
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=225, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=150, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'user_profile_userprofile_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='nickname'),
        ),
        migrations.AddField(
            model_name='userprofiletranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='user_profile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofiletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
