# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20181031_1000'),
        ('user_profile', '0010_auto_20181028_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
