# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20181101_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilecategory',
            name='child_qty',
            field=models.IntegerField(default=0),
        ),
    ]
