# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_auto_20181129_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileemployment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofileemployment',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='userprofileemploymenttranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userprofileemploymenttranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='UserProfileEmployment',
        ),
        migrations.DeleteModel(
            name='UserProfileEmploymentTranslation',
        ),
    ]
