# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20180925_0944'),
        ('user_profile', '0014_auto_20181129_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileCountryInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_country_interest', to='user_profile.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofilecategory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to='user_profile.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilecountryinterest',
            unique_together=set([('profile', 'country')]),
        ),
    ]
