# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20181209_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilecountryinterest',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Country'),
        ),
    ]
