# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_auto_20181211_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='contact_invintation',
            new_name='contact_invitation',
        ),
        migrations.RenameField(
            model_name='usercontact',
            old_name='invintation_note',
            new_name='invitation_note',
        ),
    ]
