# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_currencyrate'),
        ('user_profile', '0019_auto_20181222_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_currency',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Currency'),
        ),
    ]
