# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_userprofile_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofilecategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofilecountryinterest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
