# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_auto_20190221_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='img',
        ),
    ]
