# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_userprofile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cognito_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, db_index=True),
        ),
    ]
