# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0029_auto_20190523_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cognito_id',
        ),
    ]
