# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0030_remove_userprofile_cognito_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileEventsQty',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eventsqty', serialize=False, to='user_profile.UserProfile')),
                ('following', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('jobposts', models.PositiveIntegerField(default=0)),
                ('publications', models.PositiveIntegerField(default=0)),
                ('offerings', models.PositiveIntegerField(default=0)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('products', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileFollower',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_profile.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userprofilefollower',
            unique_together=set([('profile', 'user')]),
        ),
    ]
