# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0032_auto_20190619_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileeventsqty',
            name='notifications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
