# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0008_auto_20190412_1542'),
        ('user_profile', '0033_userprofileeventsqty_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('show_in_profile', models.BooleanField(default=False, null=None)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='user_profile.UserProfile')),
            ],
        ),
    ]
