# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0037_auto_20190924_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileeventsqty',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofileeventsqty',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
