# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0038_auto_20190930_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileeventsqty',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
