# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0041_auto_20191006_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
