# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0044_userprofile_settings_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletranslation',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiletranslation',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiletranslation',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
