# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0047_auto_20200401_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_email',
            field=models.BooleanField(default=True),
        ),
    ]
