# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-05 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0049_useractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
