# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-05 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0050_auto_20200505_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActions',
            new_name='UserAction',
        ),
    ]
