# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0052_auto_20200505_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_companies',
            field=models.BooleanField(default=False),
        ),
    ]
