# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-14 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0053_userprofile_has_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tester',
            field=models.BooleanField(default=False),
        ),
    ]
