# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-02-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0054_userprofile_tester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.File'),
        ),
    ]
