from django.conf.urls import url
from catalog.product import views

urlpatterns = [
    url(r'^get-product_images/(?P<product>.+)/$', views.ProductImagesView.as_view()),
    url(r'^get-product_image/(?P<product>.+)/$', views.ProductImageView.as_view()),
    url(r'^create-product_image/', views.CreateProductImageView.as_view()),
    url(r'^delete-product_image/(?P<pk>.+)/$', views.DeleteProductImageView.as_view()),
    url(r'^get-product-details/(?P<pk>[0-9]+)/(?P<current_currency>.+)/$', views.ProductDetailsView.as_view()),
    url(r'^get-product-details-in-language/(?P<pk>[0-9]+)/(?P<language>.+)/(?P<current_currency>.+)/$',
        views.ProductDetailsInLanguageView.as_view()),
    url(r'^get-product-by-slug/(?P<subject>.+)/(?P<sslug>.+)/(?P<slug>.+)/(?P<current_currency>.+)/$',
        views.ProductBySlugView.as_view()),
    url(r'^update-product-details/(?P<pk>[0-9]+)/(?P<language>.+)/$', views.UpdateProductDetailsView.as_view()),
    url(r'^create-product/', views.CreateProductView.as_view()),
    url(r'^delete-product/(?P<pk>.+)/$', views.DeleteProductView.as_view()),
    url(r'^create-product-group/', views.CreateProductGroupView.as_view()),
    url(r'^update-product-group/(?P<pk>[0-9]+)/(?P<language>.+)/$', views.UpdateProductGroupView.as_view()),
    url(r'^delete-product-group/(?P<pk>[0-9]+)/$', views.DeleteProductGroupView.as_view()),
    url(r'^get-company-child-product-groups/(?P<company>.+)/(?P<parent>.+)/(?P<language>.+)/$',
        views.CompanyChildProductGroupsView.as_view()),
    url(r'^get-user-child-product-groups/(?P<user>.+)/(?P<parent>.+)/(?P<language>.+)/$',
        views.UserChildProductGroupsView.as_view()),
    url(r'^search-company-product-groups/(?P<company>.+)/(?P<name>.+)/$',
        views.SearchCompanyProductGroupsView.as_view()),
    url(r'^search-user-product-groups/(?P<user>.+)/(?P<name>.+)/$',
        views.SearchUserProductGroupsView.as_view()),
    url(r'^user-products-by-page/(?P<user>.+)/(?P<page>[0-9]+)/(?P<current_currency>.+)/$',
        views.UserProductsByPageView.as_view()),
    url(r'^user-products-by-page-default-lang/(?P<user>.+)/(?P<page>[0-9]+)/(?P<current_currency>.+)/$',
        views.UserProductsByPageDefaultLangView.as_view()),
    url(r'^current-user-products-by-page/(?P<page>[0-9]+)/(?P<current_currency>.+)/$',
        views.CurrentUserProductsByPageView.as_view()),
    url(r'^products-by-page/(?P<page>[0-9]+)/$', views.ProductsByPageView.as_view()),
    url(r'^create-favorite-product/', views.CreateFavoriteProductView.as_view()),
    url(r'^delete-favorite-product/(?P<product>[0-9]+)/$', views.DeleteFavoriteProductView.as_view()),
    url(r'^favorite-products-by-page/(?P<page>[0-9]+)/$', views.FavoriteProductsByPageView.as_view()),
]
