# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='companytranslation',
            name='headline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
