# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 12:10
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181024_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=True, populate_from='name'),
            preserve_default=False,
        ),
    ]
