# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 09:56
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, null=True, populate_from='name'),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together=set([('company', 'user')]),
        ),
    ]
