# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20181031_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
