# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20181101_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycategory',
            name='child_qty',
            field=models.IntegerField(default=0),
        ),
    ]
