# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20190221_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
    ]
