# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_image'),
        ('company', '0012_remove_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file.UserImage'),
        ),
    ]
