# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 11:05
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('company', '0015_auto_20190416_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
