# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 11:15
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20190523_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True),
        ),
    ]
