# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20190604_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEventsQty',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eventsqty', serialize=False, to='company.Company')),
                ('followers', models.PositiveIntegerField(default=0)),
                ('employees', models.PositiveIntegerField(default=0)),
                ('students', models.PositiveIntegerField(default=0)),
                ('jobposts', models.PositiveIntegerField(default=0)),
                ('publications', models.PositiveIntegerField(default=0)),
                ('offerings', models.PositiveIntegerField(default=0)),
                ('products', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
