# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_companyeventsqty_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
