# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20190619_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyeventsqty',
            name='new_customer_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='new_job_responds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='new_messages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='new_offering_reponds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='new_request_responds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='open_customer_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='your_open_offering_responds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='your_open_request_responds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='your_open_supply_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
