# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20190924_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyeventsqty',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
