# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20190930_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyeventsqty',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
