# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20191001_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyeventsqty',
            name='questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
