# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-06 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_companyeventsqty_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyeventsqty',
            name='related_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyeventsqty',
            name='related_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
