# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20191006_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='favoritecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
