# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_companyuser_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='companyeventsqty',
            name='followers',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='companyeventsqty',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='companyeventsqty',
            name='related_reviews',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
