# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_auto_20191216_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyindustry',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='companysize',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='companytype',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
