# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0034_auto_20200216_1358'),
        ('company', '0031_auto_20200107_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySEOData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.City')),
                ('company_industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyIndustry')),
                ('company_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyType')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Country')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='companyseodata',
            unique_together=set([('category', 'country', 'city', 'company_type', 'company_industry')]),
        ),
    ]
