# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20200223_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyindustrytranslation',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='industryclassification',
            name='name_en',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='industryclassification',
            name='name_ru',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='industryclassification',
            name='name_uk',
            field=models.CharField(max_length=60),
        ),
    ]
