# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_auto_20200223_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseodata',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
