# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_companyseodata_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytranslation',
            name='seo_description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='companytranslation',
            name='seo_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
