# Generated by Django 2.1 on 2018-09-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_uilanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UILanguageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'general_uilanguage_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='uilanguage',
            name='name',
        ),
        migrations.AddField(
            model_name='uilanguagetranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='general.UILanguage'),
        ),
        migrations.AlterUniqueTogether(
            name='uilanguagetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
