# Generated by Django 2.1 on 2018-09-10 19:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20180910_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uilanguage',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='uilanguage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
