# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20180911_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uilanguagetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='uilanguagetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='UILanguage',
        ),
        migrations.DeleteModel(
            name='UILanguageTranslation',
        ),
    ]
