# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20180914_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='UILanguage',
        ),
        migrations.RenameModel(
            old_name='LanguageTranslation',
            new_name='UILanguageTranslation',
        ),
        migrations.AlterModelTable(
            name='uilanguagetranslation',
            table='general_uilanguage_translation',
        ),
    ]
