# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20180914_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UILanguage',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='UILanguageTranslation',
            new_name='LanguageTranslation',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('translatons__name',)},
        ),
        migrations.AlterModelTable(
            name='languagetranslation',
            table='general_language_translation',
        ),
    ]
