# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20180914_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='test',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
