# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0019_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytranslation',
            name='short_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
