# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0020_countrytranslation_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emblem', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('head_photo', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CityTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='general.City')),
            ],
            options={
                'db_table': 'general_city_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='citytranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
