# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_auto_20181031_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='general.Currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Currency')),
            ],
        ),
    ]
