# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0022_currencyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
    ]
