# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0023_auto_20181226_1249'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together=set([('currency', 'currency_to')]),
        ),
    ]
