# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0025_auto_20190212_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='companies_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='posts_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='products_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='users_exist',
            field=models.BooleanField(default=False),
        ),
    ]
