# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0026_auto_20190212_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='communities_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='communities_exist',
            field=models.BooleanField(default=False),
        ),
    ]
