# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0028_auto_20190717_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobfunction',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='senioritylabel',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='jobfunction',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senioritylabel',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
