# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0029_auto_20190718_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfunctiontranslation',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
