# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0031_auto_20190719_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobfunction',
            options={'base_manager_name': '_plain_manager'},
        ),
    ]
