# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0033_auto_20191021_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
