# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0035_auto_20191219_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='geoname_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
