# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0037_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
