# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0038_auto_20191219_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
