# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0039_auto_20191220_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='default_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
