# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0040_auto_20191220_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='default_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='geoname_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
