# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0041_auto_20191220_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(blank=True, max_length=60, null=True)),
                ('geoname_id', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=60, null=True)),
                ('timezone', models.CharField(blank=True, max_length=35, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Country')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='general.Region')),
            ],
            options={
                'db_table': 'general_region_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
