# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0042_auto_20191220_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytranslation',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
