# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0043_auto_20191220_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='timezone',
        ),
    ]
