# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0044_remove_region_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default=0, max_digits=19, null=True),
        ),
    ]
