# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0046_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='number',
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
