# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0047_currency_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='default_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
