# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0048_currency_default_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='currencytranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
