# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0049_auto_20191223_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citytranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='countrytranslation',
            name='short_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='regiontranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
