# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0051_auto_20191226_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfunction',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='senioritylabel',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
