# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0052_auto_20200107_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
    ]
