# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0054_auto_20200216_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTypeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=40)),
                ('name_en_pl', models.CharField(max_length=40)),
                ('name_ru', models.CharField(max_length=40)),
                ('name_ru_pl', models.CharField(max_length=40)),
                ('name_uk', models.CharField(max_length=40)),
                ('name_uk_pl', models.CharField(max_length=40)),
                ('code_en', models.CharField(max_length=10, unique=True)),
                ('code_ru', models.CharField(max_length=10, unique=True)),
                ('code_uk', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='unittypetranslation',
            name='name_plural',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
