# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0057_auto_20200223_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittypetranslation',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
