# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0058_auto_20200223_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.CharField(db_index=True, max_length=60, null=True, unique=True),
        ),
    ]
