# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20181117_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='local_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='community',
            name='moderator_check_invite',
            field=models.BooleanField(default=False),
        ),
    ]
