# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20181129_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycompany',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communityinvitation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
