# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-22 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20190221_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
