# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20190222_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
    ]
