# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20190523_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEventsQty',
            fields=[
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eventsqty', serialize=False, to='community.Community')),
                ('members', models.PositiveIntegerField(default=0)),
                ('companies', models.PositiveIntegerField(default=0)),
                ('jobposts', models.PositiveIntegerField(default=0)),
                ('publications', models.PositiveIntegerField(default=0)),
                ('offerings', models.PositiveIntegerField(default=0)),
                ('requests', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
