# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_communityeventsqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityeventsqty',
            name='invitations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
