# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_auto_20191006_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinvitation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='company.Company'),
        ),
    ]
