# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20191012_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
