# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_community_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinvitation',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='community.Community'),
        ),
    ]
