# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-13 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_auto_20191012_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinvitation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
