# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_auto_20191013_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communityeventsqty',
            name='members',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
