# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0022_currencyrate'),
        ('product', '0015_auto_20181104_1652'),
        ('file', '0003_auto_20180911_1751'),
        ('company', '0009_auto_20181210_1206'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_comment', models.TextField(blank=True, null=True)),
                ('supplier_comment', models.TextField(blank=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_request.SupplyRequestStatus')),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('charges_comment', models.CharField(blank=True, max_length=450, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=350, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canceled_requests', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Currency')),
                ('customer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_company_requests', to='company.Company')),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_user_requests', to=settings.AUTH_USER_MODEL)),
                ('supplier_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_company_requests', to='company.Company')),
                ('supplier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_user_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyRequestDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_request.SupplyRequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyRequestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_win_lost', models.CharField(blank=True, max_length=350, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_request.SupplyRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyRequestPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('supply_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_request.SupplyRequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplyrequestnote',
            unique_together=set([('supply_request', 'user')]),
        ),
    ]
