# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0003_auto_20181227_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='supplier_request_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
