# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0004_supplyrequest_supplier_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_user_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
