# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0005_auto_20181228_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
