# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0006_auto_20181228_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequestposition',
            name='supply_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='supply_request.SupplyRequest'),
        ),
    ]
