# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20190103_1606'),
        ('supply_request', '0008_auto_20181228_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequestChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='messaging.Chat')),
                ('supply_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='supply_request.SupplyRequest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplyrequestchat',
            unique_together=set([('supply_request', 'chat')]),
        ),
    ]
