# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0009_auto_20190104_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyrequestchat',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplyrequestchat',
            name='supply_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat', serialize=False, to='supply_request.SupplyRequest'),
        ),
        migrations.AlterField(
            model_name='supplyrequestdocument',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplyrequestnote',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplyrequestposition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
