# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0013_auto_20190820_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='charges_comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
