# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0014_auto_20200416_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='need_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
