# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0015_supplyrequest_need_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequeststatus',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
