# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-17 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0016_supplyrequeststatus_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='show_to_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
