# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20181210_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileemployment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
