# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_auto_20190212_1743'),
        ('employment', '0003_auto_20190221_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileemployment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.City'),
        ),
        migrations.AddField(
            model_name='userprofileemployment',
            name='city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofileemployment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Country'),
        ),
        migrations.AddField(
            model_name='userprofileemployment',
            name='education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileemployment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileemployment',
            name='present_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofileemployment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
