# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_auto_20190609_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileemployment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='user_profile.UserProfile'),
        ),
    ]
