# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0041_auto_20200927_0753'),
        ('general', '0061_auto_20200910_1246'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Country')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentProduct')),
            ],
        ),
    ]
