# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_categoryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprice',
            name='default_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
