# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-22 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0061_auto_20200910_1246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0036_auto_20200913_0931'),
        ('payments', '0003_categoryprice_default_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_payments', to='company.Company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Currency')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.PaymentProduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
