# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-24 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20201224_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryPrice',
            new_name='ProductPrice',
        ),
    ]
