# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-25 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0157_auto_20201214_1255'),
        ('general', '0061_auto_20200910_1246'),
        ('company', '0036_auto_20200913_0931'),
        ('product', '0046_auto_20201123_1535'),
        ('payments', '0006_auto_20201224_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_id', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='company.Company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.Currency')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentorder',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='promoted_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Company'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='promoted_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.Post'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='promoted_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.PaymentAccount'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.PaymentAccount'),
        ),
    ]
