# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-06 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20210105_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
    ]
