# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='callback_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
