# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181012_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
