# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_price_conditions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_interval',
        ),
        migrations.AddField(
            model_name='product',
            name='one_price',
            field=models.BooleanField(default=True),
        ),
    ]
