# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181018_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
