# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181020_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
