# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20181020_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_conditions',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='price_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
