# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20181102_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductGroup'),
        ),
    ]
