# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductGroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='product.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productgroupitem',
            unique_together=set([('product', 'group')]),
        ),
    ]
