# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20180925_0944'),
        ('product', '0014_auto_20181104_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category'),
        ),
    ]
