# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20181228_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_usd_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
