# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0008_auto_20190212_1955'),
        ('product', '0021_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('user_attribute', models.BooleanField(default=True)),
                ('multiple', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.Attribute')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value_string', models.CharField(blank=True, max_length=150, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('post_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.ProductAttribute')),
                ('value_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.AttributeValue')),
            ],
        ),
    ]
