# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20190924_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEventsQty',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='eventsqty', serialize=False, to='product.Product')),
                ('publications', models.PositiveIntegerField(default=0)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('videos', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
