# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_producteventsqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteventsqty',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
