# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_producteventsqty_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteventsqty',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
