# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20191011_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
