# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20191012_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_products', to='company.Company'),
        ),
    ]
