# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20191012_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd_to',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producteventsqty',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='producteventsqty',
            name='related_questions',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='producteventsqty',
            name='related_reviews',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
