# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20191216_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
