# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('category', '0034_auto_20200216_1358'),
        ('product', '0040_product_weight_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSEOData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.City')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Country')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productseodata',
            unique_together=set([('category', 'country', 'city')]),
        ),
    ]
