# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20200217_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='productseodata',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
