# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0035_suggestedcategory'),
        ('product', '0042_productseodata_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.SuggestedCategory'),
        ),
    ]
