# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_request', '0013_auto_20190820_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply_request.SupplyRequestStatus'),
        ),
    ]
