# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20181219_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
