# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20181219_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_chat', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='message',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
