# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20181224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatparticipant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_chats', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
