# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-03 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20181224_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='post',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='supply_request',
        ),
    ]
