# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20190103_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, '1. Message'), (2, '2. Contact invitation'), (3, '3. Contact accepted'), (4, '4. Community invitation'), (5, '5. New Request')], default=1),
        ),
    ]
