# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20190221_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.IntegerField(choices=[(1, '1. Contact'), (2, '2. Request'), (3, '3. Post'), (4, '4. Offering'), (5, '5. Job')], default=1),
        ),
    ]
