# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20190724_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.IntegerField(choices=[(1, '1. Contact'), (2, '2. Request'), (3, '3. Post'), (4, '4. Offering'), (5, '5. Job'), (6, '6. Post request')], default=1),
        ),
    ]
