# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_auto_20190819_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='supplier',
            field=models.BooleanField(default=False),
        ),
    ]
