# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_auto_20190820_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, '1. Message'), (2, '2. Contact invitation'), (3, '3. Contact accepted'), (4, '4. Community invitation'), (5, '5. New Request'), (6, '6. Job Response'), (7, '7. Post Response')], default=1),
        ),
    ]
