# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.IntegerField(choices=[(1, '1. number'), (2, '2. list'), (3, '3. string'), (4, '4. boolean')], default=1),
        ),
    ]
