# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-07 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_auto_20190206_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeValues',
            new_name='AttributeValue',
        ),
        migrations.RenameModel(
            old_name='AttributeValuesTranslation',
            new_name='AttributeValueTranslation',
        ),
        migrations.AlterModelTable(
            name='attributevaluetranslation',
            table='attribute_attributevalue_translation',
        ),
    ]
