# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20190207_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.IntegerField(choices=[(1, '1. list'), (2, '2. number'), (3, '3. string'), (4, '4. boolean'), (5, '5. integer')], default=1),
        ),
    ]
