# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_auto_20190209_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=12, null=True),
        ),
    ]
