# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0006_auto_20190212_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='min',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='step',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
