# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0007_auto_20190212_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='max',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='min',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='step',
        ),
    ]
