# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0060_auto_20200327_0612'),
        ('attribute', '0009_auto_20200606_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeclassification',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributeclassification',
            name='type',
            field=models.IntegerField(choices=[(1, '1. list'), (2, '2. number'), (3, '3. string'), (4, '4. boolean'), (5, '5. integer')], default=1),
        ),
        migrations.AddField(
            model_name='attributeclassification',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.UnitType'),
        ),
    ]
