# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0010_auto_20200608_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
