# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagqty',
            name='followers',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
