# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 08:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_name',
            field=models.CharField(default='1', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='232', editable=False, populate_from='default_name'),
            preserve_default=False,
        ),
    ]
