# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180924_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
