# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20180924_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='position',
        ),
    ]
