# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20180924_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='default_name',
        ),
    ]
