# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_category_default_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
