# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='childs_qty',
            field=models.IntegerField(default=0),
        ),
    ]
