# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_childs_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='childs_qty',
            new_name='child_qty',
        ),
    ]
