# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_categorytranslation_name_with_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name_with_parent',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
