# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
        ('category', '0012_auto_20180925_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_attribute', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.Attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='category.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='categoryattribute',
            unique_together=set([('category', 'attribute')]),
        ),
    ]
