# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0027_auto_20190212_1743'),
        ('category', '0014_auto_20190212_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='category.Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='general.City')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='category.Category')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='general.Country')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='categorycountry',
            unique_together=set([('category', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='categorycity',
            unique_together=set([('category', 'city')]),
        ),
    ]
