# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_auto_20190217_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
