# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_category_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content_exists',
            field=models.BooleanField(default=False),
        ),
    ]
