# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_category_content_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_name',
            field=models.CharField(default='name', max_length=60),
            preserve_default=False,
        ),
    ]
