# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_categoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livel1_code', models.CharField(max_length=15)),
                ('livel1_en_name', models.CharField(max_length=100)),
                ('livel1_ru_name', models.CharField(max_length=100)),
                ('livel1_uk_name', models.CharField(max_length=100)),
                ('livel2_code', models.CharField(max_length=15)),
                ('livel2_en_name', models.CharField(max_length=100)),
                ('livel2_ru_name', models.CharField(max_length=100)),
                ('livel2_uk_name', models.CharField(max_length=100)),
                ('livel3_code', models.CharField(max_length=15)),
                ('livel3_en_name', models.CharField(max_length=100)),
                ('livel3_ru_name', models.CharField(max_length=100)),
                ('livel3_uk_name', models.CharField(max_length=100)),
                ('livel4_code', models.CharField(max_length=15)),
                ('livel4_en_name', models.CharField(max_length=100)),
                ('livel4_ru_name', models.CharField(max_length=100)),
                ('livel4_uk_name', models.CharField(max_length=100)),
                ('livel5_code', models.CharField(max_length=15)),
                ('livel5_en_name', models.CharField(max_length=100)),
                ('livel5_ru_name', models.CharField(max_length=100)),
                ('livel5_uk_name', models.CharField(max_length=100)),
                ('livel6_code', models.CharField(max_length=15)),
                ('livel6_en_name', models.CharField(max_length=100)),
                ('livel6_ru_name', models.CharField(max_length=100)),
                ('livel6_uk_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='external_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
