# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0026_auto_20200210_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel1_en_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel1_ru_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel1_uk_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel2_en_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel2_ru_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel2_uk_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel3_en_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel3_ru_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel3_uk_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel4_en_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel4_ru_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel4_uk_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel5_en_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel5_ru_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel5_uk_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel6_en_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel6_ru_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='livel6_uk_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
