# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0027_auto_20200210_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel1_code',
            new_name='level1_code',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel1_en_name',
            new_name='level1_en_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel1_ru_name',
            new_name='level1_ru_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel1_uk_name',
            new_name='level1_uk_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel2_code',
            new_name='level2_code',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel2_en_name',
            new_name='level2_en_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel2_ru_name',
            new_name='level2_ru_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel2_uk_name',
            new_name='level2_uk_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel3_code',
            new_name='level3_code',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel3_en_name',
            new_name='level3_en_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel3_ru_name',
            new_name='level3_ru_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel3_uk_name',
            new_name='level3_uk_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel4_code',
            new_name='level4_code',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel4_en_name',
            new_name='level4_en_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel4_ru_name',
            new_name='level4_ru_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel4_uk_name',
            new_name='level4_uk_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel5_code',
            new_name='level5_code',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel5_en_name',
            new_name='level5_en_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel5_ru_name',
            new_name='level5_ru_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel5_uk_name',
            new_name='level5_uk_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel6_code',
            new_name='level6_code',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel6_en_name',
            new_name='level6_en_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel6_ru_name',
            new_name='level6_ru_name',
        ),
        migrations.RenameField(
            model_name='categoryclassification',
            old_name='livel6_uk_name',
            new_name='level6_uk_name',
        ),
    ]
