# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0030_auto_20200211_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
