# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0031_auto_20200212_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='first_level',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='content_exists',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
