# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-15 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0032_auto_20200212_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='communities_exist',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='companies_exist',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='posts_exist',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='products_exist',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='users_exist',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
