# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0033_auto_20200215_0914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorycity',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='categorycity',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorycity',
            name='city',
        ),
        migrations.AlterUniqueTogether(
            name='categorycountry',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='categorycountry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categorycountry',
            name='country',
        ),
        migrations.DeleteModel(
            name='CategoryCity',
        ),
        migrations.DeleteModel(
            name='CategoryCountry',
        ),
    ]
