# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0034_auto_20200216_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_child_set', to='category.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
