# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0035_suggestedcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcategory',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='category.Category'),
        ),
        migrations.AddField(
            model_name='suggestedcategory',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
