# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0036_auto_20200426_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedcategory',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestedcategory',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
