# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0037_auto_20200426_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryclassification',
            name='level1_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryclassification',
            name='level2_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryclassification',
            name='level3_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryclassification',
            name='level4_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryclassification',
            name='level5_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categoryclassification',
            name='level6_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level1_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level1_en_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level2_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level2_en_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level3_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level3_en_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level4_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level4_en_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level5_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level5_en_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level6_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryclassification',
            name='level6_en_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
