# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 07:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0040_auto_20200608_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, populate_from='default_name'),
        ),
    ]
